# ============================================================
# make_supp_tables.R
# Axis-stratified sub-tables for the supplementary appendix
# of the LMM Gaussian Bayesian manuscript.
#
# Produces .tex files in `theory/` that can be \input'd directly:
#   - tab_supp_by_n.tex    — F1, Recall, Precision, K_hat per (n × σg² × method)
#   - tab_supp_by_rho.tex
#   - tab_supp_by_arch.tex
#   - tab_supp_by_m.tex
#
# Plus combined recall–precision figures per axis.
# ============================================================

suppressPackageStartupMessages({
  library(dplyr); library(tidyr); library(ggplot2); library(scales)
})

OUT <- "results/bench_full"
dir.create("theory", showWarnings = FALSE)
TEX_OUT <- "theory"

METHOD_ORDER <- c("JS_L_eBIC", "MS_L_eBIC",
                   "JS_L_JP99", "MS_L_JP99",
                   "BSLMM", "BayesR", "SuSiE", "fastlmm")
METHOD_LATEX <- c(
  JS_L_eBIC     = "\\textsc{JS\\_L} (eBIC)",
  MS_L_eBIC     = "\\textsc{MS\\_L} (eBIC)",
  JS_L_JP99     = "\\textsc{JS\\_L} (JP99)",
  MS_L_JP99     = "\\textsc{MS\\_L} (JP99)",
  BSLMM         = "BSLMM",
  BayesR        = "BayesR",
  SuSiE         = "SuSiE",
  fastlmm       = "FaST-LMM"
)
# Sample-size floor: skip n=500 cells (undersized regime).
N_FLOOR <- 1000L


# -- Build sub-table for one axis ------------------------------------
make_supp_subtable <- function(axis, axis_var, axis_label,
                                  out_tex_name) {
  fn <- file.path(OUT, paste0(axis, "_summary.csv"))
  if (!file.exists(fn)) {
    message("(skipped ", axis, ": ", fn, " not found)")
    return(invisible(NULL))
  }
  df <- read.csv(fn)
  # Drop REML_stepwise (kept only as a documented failure baseline) and any rows
  # below the sample-size floor (skip n=500 cells).
  df <- df[df$method != "REML_stepwise", , drop = FALSE]
  if ("n" %in% names(df)) df <- df[df$n >= N_FLOOR, , drop = FALSE]
  # Filter to methods we want to display (drops varbvs, BL, and any other excluded)
  df <- df[df$method %in% METHOD_ORDER, , drop = FALSE]
  df$method <- factor(df$method, levels = METHOD_ORDER)
  df <- df %>% arrange(across(any_of(axis_var)), sigma_g2, method)
  fmt <- function(x) sprintf("%.2f", x)

  body_lines <- c()
  current_facet <- ""
  for (i in seq_len(nrow(df))) {
    fac <- sprintf("%s = %s, $\\sigma_g^2 = %.1f$",
                    axis_label, df[[axis_var]][i], df$sigma_g2[i])
    if (fac != current_facet) {
      if (i > 1L) body_lines <- c(body_lines, "\\midrule")
      body_lines <- c(body_lines,
        sprintf("\\multicolumn{5}{c}{\\textbf{%s}} \\\\",
                fac))
      current_facet <- fac
    }
    body_lines <- c(body_lines, sprintf(
      "%s & %s & %s & %s & %s \\\\",
      METHOD_LATEX[as.character(df$method[i])],
      fmt(df$mean_f1[i]),
      fmt(df$mean_recall[i]),
      fmt(df$mean_precision[i]),
      fmt(df$mean_K_hat[i])))
  }
  preamble <- c(
    "% AUTO-GENERATED by make_supp_tables.R",
    "\\begin{tabular}{lrrrr}",
    "\\toprule",
    "Method & $\\overline{F_1}$ & Recall & Precision & $\\overline{\\hat K}$ \\\\",
    "\\midrule")
  postamble <- c("\\bottomrule", "\\end{tabular}")
  writeLines(c(preamble, body_lines, postamble),
             file.path(TEX_OUT, out_tex_name))
  message("Wrote ", out_tex_name)
}


make_supp_subtable("01_scaling_n",   "n",      "$n$",
                     "tab_supp_by_n.tex")
make_supp_subtable("02_scaling_rho", "rho",    "$\\rho$",
                     "tab_supp_by_rho.tex")
make_supp_subtable("03_arch",        "signal", "Signal",
                     "tab_supp_by_arch.tex")
make_supp_subtable("04_scaling_m",   "m",      "$m$",
                     "tab_supp_by_m.tex")

cat("\nAll supplementary sub-tables generated in theory/\n")
