# ==============================================================================
# make_tau2_table.R
# Aggregate the tau^2 sensitivity into a LaTeX subtable.
# Input:  results/bench_full/11_tau2_sensitivity_summary.csv
# Output: theory/tab_tau2_sensitivity.tex
# ==============================================================================

IN  <- "results/bench_full/11_tau2_sensitivity_summary.csv"
dir.create("theory", showWarnings = FALSE)
TEX <- "theory/tab_tau2_sensitivity.tex"

if (!file.exists(IN)) {
  message("(skipped: ", IN, " not found)"); quit("no", status = 0L)
}

df <- read.csv(IN)
df$method_label <- ifelse(df$method == "MS_L_eBIC",
                           "\\textsc{MS-LMM}-eBIC",
                           "\\textsc{JS-LMM}-eBIC")

# Wide format: rows = (method, tau^2), columns = (F1, K_hat) × sigma_g2
suppressPackageStartupMessages(library(dplyr)); library(tidyr)
wide <- df %>%
  select(method_label, tau2, sigma_g2, mean_f1, mean_K_hat) %>%
  pivot_wider(id_cols = c(method_label, tau2),
                names_from = sigma_g2,
                values_from = c(mean_f1, mean_K_hat),
                names_sep = "_") %>%
  arrange(method_label, tau2)

fmt3 <- function(x) if (is.na(x)) "---" else sprintf("%.3f", x)
fmt1 <- function(x) if (is.na(x)) "---" else sprintf("%.1f", x)

rows <- character()
for (i in seq_len(nrow(wide))) {
  r <- wide[i, ]
  rows[i] <- sprintf("%s & %.2f & %s & %s & %s & %s \\\\",
                       r$method_label, r$tau2,
                       fmt3(r$mean_f1_0), fmt1(r$mean_K_hat_0),
                       fmt3(r$mean_f1_0.5), fmt1(r$mean_K_hat_0.5))
}

body <- c(
  "% AUTO-GENERATED by make_tau2_table.R",
  "\\begin{tabular}{l c rr@{\\hspace{12pt}} rr}",
  "\\toprule",
  "& & \\multicolumn{2}{c}{$\\sigma_g^2 = 0$}",
  "& \\multicolumn{2}{c}{$\\sigma_g^2 = 0.5$} \\\\",
  "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
  "Method & $\\tau^2$ & $\\overline{F_1}$ & $\\overline{\\hat K}$",
  "       & $\\overline{F_1}$ & $\\overline{\\hat K}$ \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}"
)
writeLines(body, TEX)
message("Wrote ", TEX)
