# ==============================================================================
# make_bmi_sex_table.R
# Combine the 4 mouse BMI analyses (with/without X chromosome ×
# with/without sex covariate) into a single LaTeX comparison table.
# ==============================================================================

# Read all 4 CSVs
CSVs <- list(
  whole_no_sex = list(file = "results/bench_full/06_realdata_mice_wholegenome_summary.csv",
                        col_method = "method", scope = "whole, no sex"),
  whole_sex    = list(file = "results/bench_full/15_mouse_bmi_with_sex_summary.csv",
                        col_method = "method", scope_filter = "whole_with_sex",
                        scope = "whole, with sex"),
  aut_no_sex   = list(file = "results/bench_full/12_mouse_autosomes_summary.csv",
                        col_method = "method", scope = "autosomes, no sex"),
  aut_sex      = list(file = "results/bench_full/15_mouse_bmi_with_sex_summary.csv",
                        col_method = "method", scope_filter = "autosomes_with_sex",
                        scope = "autosomes, with sex")
)
# fastlmm has its own 4-scope CSV (run by /tmp/run_fastlmm_4scopes.R; see
# results/bench_full/fastlmm_bmi_4scopes.csv).
CSVs_fastlmm <- list(
  file = "results/bench_full/fastlmm_bmi_4scopes.csv",
  scope_col = "scope",
  scopes = c(whole_no_sex = "whole_no_sex",
             whole_sex    = "whole_with_sex",
             aut_no_sex   = "autosomes_no_sex",
             aut_sex      = "autosomes_with_sex"))

METHOD_ORDER <- c("JS_L_eBIC", "MS_L_eBIC", "JS_L_JP99", "MS_L_JP99",
                   "BayesR", "BSLMM", "SuSiE", "fastlmm")
METHOD_LATEX <- c(
  JS_L_eBIC = "\\textsc{JS-LMM}-eBIC",
  MS_L_eBIC = "\\textsc{MS-LMM}-eBIC",
  JS_L_JP99 = "\\textsc{JS-LMM}-JP99",
  MS_L_JP99 = "\\textsc{MS-LMM}-JP99",
  BayesR    = "BayesR",
  BSLMM     = "BSLMM",
  SuSiE     = "SuSiE",
  fastlmm   = "FaST-LMM"
)

# Build a table: rows = method, columns = (chr distribution) × 4 scopes
get_chr_str <- function(cfg, mname) {
  if (!file.exists(cfg$file)) return("---")
  df <- read.csv(cfg$file, stringsAsFactors = FALSE)
  if (!is.null(cfg$scope_filter))
    df <- df[df$scope == cfg$scope_filter, ]
  r <- df[df[[cfg$col_method]] == mname, ]
  if (nrow(r) == 0L) return("---")
  s <- r$chr_distribution[1]
  if (is.null(s) || is.na(s) || s == "" || s == "(none)") return("(none)")
  s
}

rows <- character()
for (mname in METHOD_ORDER) {
  cells <- sapply(CSVs, function(cfg) get_chr_str(cfg, mname))
  rows[length(rows) + 1L] <- sprintf("%s & %s & %s & %s & %s \\\\",
                                         METHOD_LATEX[mname],
                                         cells[["whole_no_sex"]],
                                         cells[["whole_sex"]],
                                         cells[["aut_no_sex"]],
                                         cells[["aut_sex"]])
}

body <- c(
  "% AUTO-GENERATED by make_bmi_sex_table.R",
  "\\begin{tabular}{l l l l l}",
  "\\toprule",
  "& \\multicolumn{2}{c}{Whole genome} & \\multicolumn{2}{c}{Autosomes only} \\\\",
  "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
  "Method & no sex & with sex & no sex & with sex \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}"
)
dir.create("theory", showWarnings = FALSE)
writeLines(body, "theory/tab_bmi_sex_comparison.tex")
message("Wrote theory/tab_bmi_sex_comparison.tex")
