# ==============================================================================
# make_mixtau_table.R
# Generate LaTeX subtable comparing mixture-slab variants.
# Input:  results/bench_full/13_mixtau_summary.csv
# Output: theory/tab_mixtau.tex
# ==============================================================================

IN  <- "results/bench_full/13_mixtau_summary.csv"
dir.create("theory", showWarnings = FALSE)
TEX <- "theory/tab_mixtau.tex"

if (!file.exists(IN)) {
  message("(skipped: ", IN, " not found)"); quit("no", status = 0L)
}

suppressPackageStartupMessages({ library(dplyr); library(tidyr) })
df <- read.csv(IN, stringsAsFactors = FALSE)

CONFIG_LABEL <- c(
  std_004      = "$\\tau^2 = 0.04$",
  mix_uniform  = "Mix uniform",
  mix_polybias = "Mix poly-biased"
)
VARIANT_LABEL <- c(
  MS_L = "\\textsc{MS-LMM}",
  JS_L = "\\textsc{JS-LMM}"
)

# We focus on a single variant (MS_L) for compactness; JS_L results are very close
df_ms <- df[df$variant == "MS_L", ]
df_ms$config <- factor(df_ms$config, levels = names(CONFIG_LABEL))
df_ms$cell   <- factor(df_ms$cell,
                          levels = c("anchor_sg0", "anchor_sg0.5",
                                       "weak_sg0.5", "n3000_sg0.5",
                                       "rho098_sg0"))
df_ms <- df_ms %>% arrange(cell, config)

fmt3 <- function(x) if (is.na(x)) "---" else sprintf("%.3f", x)
fmt1 <- function(x) if (is.na(x)) "---" else sprintf("%.1f", x)

rows <- character()
prev_cell <- ""
for (i in seq_len(nrow(df_ms))) {
  r <- df_ms[i, ]
  cell_lbl <- if (as.character(r$cell) != prev_cell) {
    prev_cell <- as.character(r$cell)
    sprintf("\\multirow{3}{*}{%s}", prev_cell)
  } else ""
  rows[length(rows)+1L] <- sprintf("%s & %s & %s & %s & %s & %s \\\\",
                                       cell_lbl,
                                       CONFIG_LABEL[as.character(r$config)],
                                       fmt3(r$mean_f1),
                                       fmt3(r$mean_recall),
                                       fmt3(r$mean_precision),
                                       fmt1(r$mean_K_hat))
  if (i %% 3L == 0L && i < nrow(df_ms)) rows[length(rows)+1L] <- "\\midrule"
}

body <- c(
  "% AUTO-GENERATED by make_mixtau_table.R",
  "\\begin{tabular}{l l rrr r}",
  "\\toprule",
  "Cell & Slab prior & $\\overline{F_1}$ & Recall & Precision & $\\overline{\\hat K}$ \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}"
)
writeLines(body, TEX)
message("Wrote ", TEX)

# Summary stats
cat("\n--- Mixture-slab summary (MS_L variant) ---\n")
print(df_ms %>% select(cell, config, mean_f1, mean_recall, mean_precision, mean_K_hat))
