# ============================================================
# make_runtime_table.R
# Wall-clock runtime comparison per method, stratified by n.
# Output: theory/tab_runtime.tex (LaTeX subtable for §11.2)
#
# Uses the `elapsed` column of all RDS files in
# results/bench_full/0[1-4]_*/.  Stratifies by n (single column for
# rho, signal, m axes pooled at their anchor n=1000) so the table
# stays compact: 9 rows × 3 n-columns.
# ============================================================

suppressPackageStartupMessages({
  library(dplyr); library(tidyr)
})

OUT <- "results/bench_full"
dir.create("theory", showWarnings = FALSE)
TEX <- "theory/tab_runtime.tex"

# REML_stepwise excluded — see make_aggregate_table.R for the rationale.
METHOD_ORDER <- c("JS_L_eBIC", "JS_L_JP99",
                   "MS_L_eBIC", "MS_L_JP99",
                   "BayesR", "BSLMM", "SuSiE", "fastlmm")
METHOD_LATEX <- c(
  JS_L_eBIC     = "\\textsc{JS-LMM}-eBIC",
  MS_L_eBIC     = "\\textsc{MS-LMM}-eBIC",
  JS_L_JP99     = "\\textsc{JS-LMM}-JP99",
  MS_L_JP99     = "\\textsc{MS-LMM}-JP99",
  BayesR        = "BayesR",
  BSLMM         = "BSLMM",
  SuSiE         = "SuSiE",
  fastlmm       = "FaST-LMM"
)

# Pool all axis raw CSVs, retaining elapsed + n
dfs <- list()
for (tag in c("01_scaling_n", "02_scaling_rho", "03_arch", "04_scaling_m")) {
  fn <- file.path(OUT, paste0(tag, "_raw.csv"))
  if (!file.exists(fn)) next
  d <- read.csv(fn)
  dfs[[tag]] <- d[, intersect(c("method", "elapsed", "n", "sigma_g2"), names(d)),
                    drop = FALSE]
}
all_df <- do.call(rbind, dfs)
# Exclude REML_stepwise from the runtime table (see make_aggregate_table.R).
all_df <- all_df[all_df$method != "REML_stepwise", , drop = FALSE]

# Average elapsed per method × n (pooling sigma_g2 and other axes at common n)
agg <- all_df %>%
  group_by(method, n) %>%
  summarise(elapsed_med = median(elapsed, na.rm = TRUE),
            elapsed_mean = mean(elapsed, na.rm = TRUE),
            n_obs = n(),
            .groups = "drop") %>%
  arrange(method, n)

cat("Per-(method, n) runtime aggregate:\n")
print(agg, n = 30)

# Wide format for table: rows = method, columns = n
wide <- agg %>%
  pivot_wider(id_cols = method,
                names_from = n,
                values_from = elapsed_med,
                names_prefix = "n_")
wide$method <- factor(wide$method, levels = METHOD_ORDER)
wide <- wide %>% arrange(method)

# Format helper: scientific notation for >100s, otherwise 1 decimal
fmt_time <- function(s) {
  if (is.na(s)) return("---")
  if (s < 1)        return(sprintf("%.2f", s))
  if (s < 10)       return(sprintf("%.1f", s))
  if (s < 100)      return(sprintf("%.0f", s))
  return(sprintf("%.0f", s))
}

# Determine column names (n levels present)
n_cols <- grep("^n_", names(wide), value = TRUE)
n_vals <- as.integer(sub("^n_", "", n_cols))

rows <- character()
for (i in seq_len(nrow(wide))) {
  r <- wide[i, ]
  cells <- sapply(n_cols, function(c) fmt_time(as.numeric(r[[c]])))
  rows[i] <- sprintf("%s & %s \\\\",
                       METHOD_LATEX[as.character(r$method)],
                       paste(cells, collapse = " & "))
}

header <- sprintf("Method & %s \\\\",
                    paste(sprintf("$n=%s$", format(n_vals, big.mark = ",")),
                          collapse = " & "))

body <- c(
  "% AUTO-GENERATED by make_runtime_table.R",
  sprintf("\\begin{tabular}{l%s}",
           paste(rep("r", length(n_cols)), collapse = "")),
  "\\toprule",
  header,
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}")
writeLines(body, TEX)
message("Wrote ", TEX)
