# ============================================================
# make_aggregate_table.R
# Pool the four axis summaries (n>=1000) into a single
# aggregate-by-(method × σg²) table for Section 11.2 of the manuscript.
# Output: theory/tab_aggregate_main.tex
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
})

OUT <- "results/bench_full"
dir.create("theory", showWarnings = FALSE)
TEX <- "theory/tab_aggregate_main.tex"
N_FLOOR <- 1000L

# REML_stepwise is excluded from the main aggregate table (uniform F1=0 across
# all cells under strong LD due to greedy in-block proximal contamination —
# documented in §10.2 / §11 narratively without consuming a table row).
METHOD_ORDER <- c("BSLMM", "BayesR",
                   "MS_L_eBIC", "JS_L_eBIC",
                   "JS_L_JP99", "MS_L_JP99",
                   "SuSiE", "fastlmm")
METHOD_LATEX <- c(
  JS_L_eBIC     = "\\textsc{JS-LMM}-eBIC",
  MS_L_eBIC     = "\\textsc{MS-LMM}-eBIC",
  JS_L_JP99     = "\\textsc{JS-LMM}-JP99",
  MS_L_JP99     = "\\textsc{MS-LMM}-JP99",
  BSLMM         = "BSLMM",
  BayesR        = "BayesR",
  SuSiE         = "SuSiE",
  fastlmm       = "FaST-LMM"
)

# -- Pool raw data and aggregate -------------------------------------
load_raw <- function(tag, key) {
  fn <- file.path(OUT, paste0(tag, "_raw.csv"))
  if (!file.exists(fn)) {
    message("(skipped: ", fn, " not found)"); return(NULL)
  }
  df <- read.csv(fn)
  if ("n" %in% names(df)) df <- df[df$n >= N_FLOOR, , drop = FALSE]
  df
}

dfs <- list(load_raw("01_scaling_n"),
              load_raw("02_scaling_rho"),
              load_raw("03_arch"),
              load_raw("04_scaling_m"))
dfs <- dfs[!sapply(dfs, is.null)]
# Reduce to common columns
common <- Reduce(intersect, lapply(dfs, names))
dfs <- lapply(dfs, function(d) d[, common, drop = FALSE])
all_df <- do.call(rbind, dfs)
# Exclude REML_stepwise from the main aggregate (see comment at top).
all_df <- all_df[all_df$method != "REML_stepwise", , drop = FALSE]
cat(sprintf("Pooled %d rows across %d cells\n",
            nrow(all_df), length(unique(paste(all_df$method, all_df$sigma_g2)))))

agg <- all_df %>%
  group_by(method, sigma_g2) %>%
  summarise(F1   = mean(f1, na.rm = TRUE),
            Rec  = mean(recall, na.rm = TRUE),
            Prec = mean(precision, na.rm = TRUE),
            K_hat = mean(K_hat, na.rm = TRUE),
            n_reps = n(),
            .groups = "drop")
agg$method <- factor(agg$method, levels = METHOD_ORDER)
agg <- agg %>% arrange(sigma_g2, method)
print(agg)

# -- Build LaTeX table -----------------------------------------------
wide <- agg %>%
  tidyr::pivot_wider(id_cols = method,
                       names_from = sigma_g2,
                       values_from = c(F1, Rec, Prec, K_hat),
                       names_sep = "_")
wide <- wide %>% arrange(desc(F1_0))

fmt <- function(x, d=3) if (is.na(x)) "---" else formatC(x, digits=d, format="f")
fmt2 <- function(x) if (is.na(x)) "---" else sprintf("%.2f", x)
fmt1 <- function(x) if (is.na(x)) "---" else sprintf("%.1f", x)

# Bold winner per (column block)
best_f1_0 <- which.max(wide$F1_0)
best_f1_5 <- which.max(wide$F1_0.5)

rows <- character()
for (i in seq_len(nrow(wide))) {
  r <- wide[i, ]
  mname <- METHOD_LATEX[as.character(r$method)]
  f1_0   <- fmt(r$F1_0)
  f1_5   <- fmt(r$F1_0.5)
  if (i == best_f1_0) f1_0 <- paste0("$\\mathbf{", f1_0, "}$")
  if (i == best_f1_5) f1_5 <- paste0("$\\mathbf{", f1_5, "}$")
  rows[i] <- sprintf(
    "%s & %s & %s & %s & %s & %s & %s & %s & %s \\\\",
    mname,
    f1_0, fmt2(r$Rec_0), fmt2(r$Prec_0), fmt1(r$K_hat_0),
    f1_5, fmt2(r$Rec_0.5), fmt2(r$Prec_0.5), fmt1(r$K_hat_0.5))
}

body <- c(
  "% AUTO-GENERATED by make_aggregate_table.R",
  "\\begin{tabular}{l rrrr@{\\hspace{12pt}} rrrr}",
  "\\toprule",
  "& \\multicolumn{4}{c}{$\\sigma_g^2 = 0$ (no polygenic)}",
  "& \\multicolumn{4}{c}{$\\sigma_g^2 = 0.5$ (polygenic background)} \\\\",
  "\\cmidrule(lr){2-5}\\cmidrule(lr){6-9}",
  "Method & $\\overline{F_1}$ & Rec.\\ & Prec.\\ & $\\overline{\\hat K}$",
  "       & $\\overline{F_1}$ & Rec.\\ & Prec.\\ & $\\overline{\\hat K}$ \\\\",
  "\\midrule",
  rows,
  "\\bottomrule",
  "\\end{tabular}")
writeLines(body, TEX)
message("Wrote ", TEX)
