# ==============================================================================
# make_threshold_indep_table.R
# Aggregate threshold-independent metrics across cells × replicates.
# Output: theory/tab_threshold_indep.tex
# ==============================================================================

suppressPackageStartupMessages({
  library(dplyr); library(tidyr)
})

IN_DIR <- "results/bench_full/10_threshold_indep"
dir.create("theory", showWarnings = FALSE)
TEX    <- "theory/tab_threshold_indep.tex"

METHOD_ORDER <- c("MS_L_eBIC", "JS_L_eBIC", "BayesR", "BSLMM", "SuSiE", "fastlmm")
METHOD_LATEX <- c(
  MS_L_eBIC = "\\textsc{MS-LMM} (top-$K^\\star$)",
  JS_L_eBIC = "\\textsc{JS-LMM} (top-$K^\\star$)",
  BayesR    = "BayesR",
  BSLMM     = "BSLMM",
  SuSiE     = "SuSiE",
  fastlmm   = "FaST-LMM"
)

files <- list.files(IN_DIR, pattern = "^(anchor|n3000|rho098).*_b\\d+\\.rds$",
                      full.names = TRUE)
if (length(files) == 0L) {
  message("No RDS files in ", IN_DIR); quit("no", status = 0L)
}

rows <- lapply(files, function(f) {
  p <- readRDS(f)
  m <- p$metrics
  rs <- list()
  for (mname in names(m)) {
    rs[[length(rs)+1L]] <- data.frame(
      cell = p$cell_tag,
      sigma_g2 = p$sigma_g2,
      method = mname,
      top_K = m[[mname]]$top_K_recall,
      pr_auc = m[[mname]]$pr_auc,
      brier = m[[mname]]$brier,
      ece = m[[mname]]$ece,
      stringsAsFactors = FALSE)
  }
  do.call(rbind, rs)
})
df <- do.call(rbind, rows)

agg <- df %>% group_by(method, sigma_g2) %>%
  summarise(top_K = mean(top_K, na.rm = TRUE),
            pr_auc = mean(pr_auc, na.rm = TRUE),
            brier = mean(brier, na.rm = TRUE),
            ece = mean(ece, na.rm = TRUE),
            n_reps = n(),
            .groups = "drop")

cat("Aggregate threshold-independent metrics:\n")
print(as.data.frame(agg))

agg$method <- factor(agg$method, levels = METHOD_ORDER)
agg <- agg %>% arrange(sigma_g2, method)

# Wide format: rows = method, columns = (top_K, pr_auc, brier, ece) × σg²
wide <- agg %>% tidyr::pivot_wider(
  id_cols = method,
  names_from = sigma_g2,
  values_from = c(top_K, pr_auc, brier, ece),
  names_sep = "_"
)
wide <- wide %>% arrange(method)

fmt <- function(x, d = 3) {
  if (is.na(x) || is.nan(x)) "---"
  else if (d == 4) sprintf("%.4f", x)
  else sprintf("%.3f", x)
}

rows_tex <- character()
for (i in seq_len(nrow(wide))) {
  r <- wide[i, ]
  rows_tex[i] <- sprintf(
    "%s & %s & %s & %s & %s & %s & %s & %s & %s \\\\",
    METHOD_LATEX[as.character(r$method)],
    fmt(r$top_K_0),    fmt(r$pr_auc_0),
    fmt(r$brier_0, 4), fmt(r$ece_0),
    fmt(r$top_K_0.5),  fmt(r$pr_auc_0.5),
    fmt(r$brier_0.5, 4), fmt(r$ece_0.5))
}

body <- c(
  "% AUTO-GENERATED by make_threshold_indep_table.R",
  "\\begin{tabular}{l rrrr@{\\hspace{8pt}} rrrr}",
  "\\toprule",
  "& \\multicolumn{4}{c}{$\\sigma_g^2 = 0$}",
  "& \\multicolumn{4}{c}{$\\sigma_g^2 = 0.5$} \\\\",
  "\\cmidrule(lr){2-5}\\cmidrule(lr){6-9}",
  "Method & Top-$K^\\star$ & PR-AUC & Brier & ECE",
  "       & Top-$K^\\star$ & PR-AUC & Brier & ECE \\\\",
  "\\midrule",
  rows_tex,
  "\\bottomrule",
  "\\end{tabular}"
)
writeLines(body, TEX)
message("Wrote ", TEX)
